/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ba.bundleimporter.datamodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BundleOut extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7705754339357403231L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BundleOut\",\"namespace\":\"ba.bundleimporter.datamodel\",\"fields\":[{\"name\":\"bundleId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BundleOut> ENCODER =
      new BinaryMessageEncoder<BundleOut>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BundleOut> DECODER =
      new BinaryMessageDecoder<BundleOut>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BundleOut> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BundleOut> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BundleOut> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BundleOut>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BundleOut to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BundleOut from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BundleOut instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BundleOut fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence bundleId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BundleOut() {}

  /**
   * All-args constructor.
   * @param bundleId The new value for bundleId
   */
  public BundleOut(java.lang.CharSequence bundleId) {
    this.bundleId = bundleId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bundleId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bundleId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bundleId' field.
   * @return The value of the 'bundleId' field.
   */
  public java.lang.CharSequence getBundleId() {
    return bundleId;
  }


  /**
   * Sets the value of the 'bundleId' field.
   * @param value the value to set.
   */
  public void setBundleId(java.lang.CharSequence value) {
    this.bundleId = value;
  }

  /**
   * Creates a new BundleOut RecordBuilder.
   * @return A new BundleOut RecordBuilder
   */
  public static ba.bundleimporter.datamodel.BundleOut.Builder newBuilder() {
    return new ba.bundleimporter.datamodel.BundleOut.Builder();
  }

  /**
   * Creates a new BundleOut RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BundleOut RecordBuilder
   */
  public static ba.bundleimporter.datamodel.BundleOut.Builder newBuilder(ba.bundleimporter.datamodel.BundleOut.Builder other) {
    if (other == null) {
      return new ba.bundleimporter.datamodel.BundleOut.Builder();
    } else {
      return new ba.bundleimporter.datamodel.BundleOut.Builder(other);
    }
  }

  /**
   * Creates a new BundleOut RecordBuilder by copying an existing BundleOut instance.
   * @param other The existing instance to copy.
   * @return A new BundleOut RecordBuilder
   */
  public static ba.bundleimporter.datamodel.BundleOut.Builder newBuilder(ba.bundleimporter.datamodel.BundleOut other) {
    if (other == null) {
      return new ba.bundleimporter.datamodel.BundleOut.Builder();
    } else {
      return new ba.bundleimporter.datamodel.BundleOut.Builder(other);
    }
  }

  /**
   * RecordBuilder for BundleOut instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BundleOut>
    implements org.apache.avro.data.RecordBuilder<BundleOut> {

    private java.lang.CharSequence bundleId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ba.bundleimporter.datamodel.BundleOut.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bundleId)) {
        this.bundleId = data().deepCopy(fields()[0].schema(), other.bundleId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BundleOut instance
     * @param other The existing instance to copy.
     */
    private Builder(ba.bundleimporter.datamodel.BundleOut other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.bundleId)) {
        this.bundleId = data().deepCopy(fields()[0].schema(), other.bundleId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'bundleId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBundleId() {
      return bundleId;
    }


    /**
      * Sets the value of the 'bundleId' field.
      * @param value The value of 'bundleId'.
      * @return This builder.
      */
    public ba.bundleimporter.datamodel.BundleOut.Builder setBundleId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bundleId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bundleId' field has been set.
      * @return True if the 'bundleId' field has been set, false otherwise.
      */
    public boolean hasBundleId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bundleId' field.
      * @return This builder.
      */
    public ba.bundleimporter.datamodel.BundleOut.Builder clearBundleId() {
      bundleId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BundleOut build() {
      try {
        BundleOut record = new BundleOut();
        record.bundleId = fieldSetFlags()[0] ? this.bundleId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BundleOut>
    WRITER$ = (org.apache.avro.io.DatumWriter<BundleOut>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BundleOut>
    READER$ = (org.apache.avro.io.DatumReader<BundleOut>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bundleId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bundleId = in.readString(this.bundleId instanceof Utf8 ? (Utf8)this.bundleId : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bundleId = in.readString(this.bundleId instanceof Utf8 ? (Utf8)this.bundleId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










